#!/bin/bash
# World Inspection Tool for Mertin-Flemmer
# Generates text-based reports and diagrams for Claude to understand the game world
# Outputs: structured data, ASCII maps, entity lists, relationship graphs

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SRC_DIR="$PROJECT_ROOT/src/mertin-flemmer"
OUTPUT_DIR="$PROJECT_ROOT/reports"

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Colors for terminal
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  MERTIN-FLEMMER WORLD INSPECTOR${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# ==========================================
# 1. WORLD LAYOUT REPORT
# ==========================================

echo -e "${BLUE}Generating world layout report...${NC}"

cat > "$OUTPUT_DIR/world-layout.md" << 'EOF'
# Mertin-Flemmer World Layout Report

Generated by inspect-world.sh

## Overview
EOF

# Extract world size
WORLD_SIZE=$(grep -o "WORLD_SIZE = [0-9]*" "$SRC_DIR/server/World.server.luau" 2>/dev/null | grep -o "[0-9]*" || echo "Unknown")
echo "- **World Size**: ${WORLD_SIZE} x ${WORLD_SIZE} studs" >> "$OUTPUT_DIR/world-layout.md"

# Extract ground info
GROUND_SIZE=$(grep -o "Size = Vector3.new([^)]*)" "$SRC_DIR/server/World.server.luau" 2>/dev/null | head -1 | sed 's/.*Vector3.new(\([^)]*\))/\1/' || echo "Unknown")
echo "- **Ground Size**: ${GROUND_SIZE}" >> "$OUTPUT_DIR/world-layout.md"
echo "" >> "$OUTPUT_DIR/world-layout.md"

# ==========================================
# 2. MOUNTAIN POSITIONS
# ==========================================

echo "## Mountains" >> "$OUTPUT_DIR/world-layout.md"
echo "" >> "$OUTPUT_DIR/world-layout.md"

if [ -f "$SRC_DIR/server/Mountains.server.luau" ]; then
    # Extract mountain data
    grep -o "name = \"[^\"]*\"" "$SRC_DIR/server/Mountains.server.luau" | while read -r line; do
        name=$(echo "$line" | sed 's/name = "\([^"]*\)"/\1/')
        echo "- $name" >> "$OUTPUT_DIR/world-layout.md"
    done

    # Extract positions
    echo "" >> "$OUTPUT_DIR/world-layout.md"
    echo "### Mountain Base Positions" >> "$OUTPUT_DIR/world-layout.md"
    echo '```' >> "$OUTPUT_DIR/world-layout.md"
    grep -o "basePosition = Vector3.new([^)]*)" "$SRC_DIR/server/Mountains.server.luau" | while read -r line; do
        pos=$(echo "$line" | sed 's/basePosition = Vector3.new(\([^)]*\))/\1/')
        echo "  Position: ($pos)" >> "$OUTPUT_DIR/world-layout.md"
    done
    echo '```' >> "$OUTPUT_DIR/world-layout.md"
fi

echo "" >> "$OUTPUT_DIR/world-layout.md"

# ==========================================
# 3. WATER BODIES
# ==========================================

echo "## Water Bodies" >> "$OUTPUT_DIR/world-layout.md"
echo "" >> "$OUTPUT_DIR/world-layout.md"

if [ -f "$SRC_DIR/server/Survival.server.luau" ]; then
    # Extract rivers
    echo "### Rivers" >> "$OUTPUT_DIR/world-layout.md"
    grep -o "name = \"[^\"]*\"" "$SRC_DIR/server/Survival.server.luau" | grep -i "river\|brook\|creek\|falls" | while read -r line; do
        name=$(echo "$line" | sed 's/name = "\([^"]*\)"/\1/')
        echo "- $name" >> "$OUTPUT_DIR/world-layout.md"
    done

    echo "" >> "$OUTPUT_DIR/world-layout.md"
    echo "### Lakes" >> "$OUTPUT_DIR/world-layout.md"
    grep -o "name = \"[^\"]*\"" "$SRC_DIR/server/Survival.server.luau" | grep -i "lake\|pond\|pool" | while read -r line; do
        name=$(echo "$line" | sed 's/name = "\([^"]*\)"/\1/')
        echo "- $name" >> "$OUTPUT_DIR/world-layout.md"
    done
fi

echo "" >> "$OUTPUT_DIR/world-layout.md"

# ==========================================
# 4. RADIO STATIONS
# ==========================================

echo "## Radio Stations" >> "$OUTPUT_DIR/world-layout.md"
echo "" >> "$OUTPUT_DIR/world-layout.md"

if [ -f "$SRC_DIR/server/Music.server.luau" ]; then
    echo "| Station | Frequency | Genre | Position | Range |" >> "$OUTPUT_DIR/world-layout.md"
    echo "|---------|-----------|-------|----------|-------|" >> "$OUTPUT_DIR/world-layout.md"

    # This is simplified - real extraction would need more parsing
    grep -A5 "name = \"" "$SRC_DIR/server/Music.server.luau" | grep -E "name|frequency|genre|position|range" | head -30 >> "$OUTPUT_DIR/world-layout.md" 2>/dev/null || echo "Parsing limited" >> "$OUTPUT_DIR/world-layout.md"
fi

echo "" >> "$OUTPUT_DIR/world-layout.md"

# ==========================================
# 5. ASCII MAP GENERATION
# ==========================================

echo -e "${BLUE}Generating ASCII world map...${NC}"

cat > "$OUTPUT_DIR/world-map.txt" << 'MAPEOF'
MERTIN-FLEMMER WORLD MAP (Approximate)
=====================================

Scale: Each character ≈ 100 studs
Origin (0,0) marked with [S] = Spawn

                    NORTH (-Z)
                       |
       -500           |          +500
         |            |            |
    .----|------------|------------|----.
    |    |            |            |    |  +500
    |    *Frozen      |    Shadow  |    |
    |    Peaks        |    Mtns    |    |
    |                 |            *    |
    |    ~~~~~        |            |    |
    |    Serpent      |            |    |
    |    River        |            |    |
----|-----------------+-[S]--------|----|--- EAST (+X)
    |                 |            |    |
    |    Whispering   |            |    |
    |    Brook ~~~    |    Ember   |    |
    |                 |    Ridge   |    |  -500
    |    *Broken      |      *     |    |
    |    Hills        |            |    |
    |                 |   Giants * |    |
    '----|------------|------------|----'
         |            |            |
       -500           |          +500
                      |
                    SOUTH (+Z)

LEGEND:
  [S] = Spawn Point (0, 0)
  *   = Mountain Range
  ~~~ = River/Water
  O   = Lake
  #   = Trading Post
  +   = Checkers Board

MOUNTAINS:
  - Frozen Peaks: NW quadrant (300, -400)
  - Shadow Mountains: NE quadrant (400, -200)
  - Ember Ridge: SE quadrant (200, 200)
  - The Giants: South central (350, 350)
  - Broken Hills: SW quadrant (-350, 300)

WATER:
  - Serpent River: Winds through western area
  - Whispering Brook: Southern region
  - Shadow Creek: Near Shadow Mountains
  - Crystal Falls: Near Frozen Peaks

RADIO TOWERS:
  @ Doom FM (66.6): Near Frozen Peaks
  @ Survivor Radio (88.1): Near spawn
  @ The Wasteland (91.7): Shadow Mountains
  @ Camel Country (103.5): Southern area
  @ Static (??.?): Far north
  @ Mountain Echo (107.9): Near The Giants

MAPEOF

# ==========================================
# 6. ENTITY INVENTORY
# ==========================================

echo -e "${BLUE}Generating entity inventory...${NC}"

cat > "$OUTPUT_DIR/entity-inventory.md" << 'EOF'
# Entity Inventory

## Server Scripts
EOF

for file in "$SRC_DIR/server"/*.luau; do
    filename=$(basename "$file")
    lines=$(wc -l < "$file" | tr -d ' ')
    echo "- **$filename** ($lines lines)" >> "$OUTPUT_DIR/entity-inventory.md"

    # Count major structures
    instances=$(grep -c "Instance.new" "$file" 2>/dev/null || echo "0")
    remotes=$(grep -c "RemoteEvent\|RemoteFunction" "$file" 2>/dev/null || echo "0")
    echo "  - Instance.new calls: $instances" >> "$OUTPUT_DIR/entity-inventory.md"
    echo "  - Remote events/functions: $remotes" >> "$OUTPUT_DIR/entity-inventory.md"
done

echo "" >> "$OUTPUT_DIR/entity-inventory.md"
echo "## Client Scripts" >> "$OUTPUT_DIR/entity-inventory.md"

for file in "$SRC_DIR/client"/*.luau; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        lines=$(wc -l < "$file" | tr -d ' ')
        echo "- **$filename** ($lines lines)" >> "$OUTPUT_DIR/entity-inventory.md"
    fi
done

echo "" >> "$OUTPUT_DIR/entity-inventory.md"
echo "## Shared Modules" >> "$OUTPUT_DIR/entity-inventory.md"

for file in "$SRC_DIR/shared"/*.luau; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        lines=$(wc -l < "$file" | tr -d ' ')
        echo "- **$filename** ($lines lines)" >> "$OUTPUT_DIR/entity-inventory.md"
    fi
done

# ==========================================
# 7. GAME CONSTANTS EXTRACTION
# ==========================================

echo -e "${BLUE}Extracting game constants...${NC}"

cat > "$OUTPUT_DIR/game-constants.md" << 'EOF'
# Game Constants

## Survival Mechanics
EOF

# Extract from shared config
if [ -f "$SRC_DIR/shared/init.luau" ]; then
    echo '```lua' >> "$OUTPUT_DIR/game-constants.md"
    grep -E "^[A-Z_]+ = [0-9]|local [A-Z_]+ = " "$SRC_DIR/shared/init.luau" 2>/dev/null | head -30 >> "$OUTPUT_DIR/game-constants.md"
    echo '```' >> "$OUTPUT_DIR/game-constants.md"
fi

echo "" >> "$OUTPUT_DIR/game-constants.md"
echo "## World Constants" >> "$OUTPUT_DIR/game-constants.md"

if [ -f "$SRC_DIR/server/World.server.luau" ]; then
    echo '```lua' >> "$OUTPUT_DIR/game-constants.md"
    grep -E "^local [A-Z_]+ = |WORLD_SIZE|GROUND" "$SRC_DIR/server/World.server.luau" 2>/dev/null | head -20 >> "$OUTPUT_DIR/game-constants.md"
    echo '```' >> "$OUTPUT_DIR/game-constants.md"
fi

# ==========================================
# 8. COMPANION SUMMARY
# ==========================================

echo -e "${BLUE}Extracting companion data...${NC}"

cat > "$OUTPUT_DIR/companions.md" << 'EOF'
# Companion Camels

## Personalities
EOF

if [ -f "$SRC_DIR/server/Companion.server.luau" ]; then
    grep -A10 "PERSONALITIES = {" "$SRC_DIR/server/Companion.server.luau" 2>/dev/null | while read -r line; do
        if echo "$line" | grep -q "name = "; then
            name=$(echo "$line" | grep -o 'name = "[^"]*"' | sed 's/name = "\([^"]*\)"/\1/')
            echo "### $name" >> "$OUTPUT_DIR/companions.md"
        fi
        if echo "$line" | grep -q "description = "; then
            desc=$(echo "$line" | grep -o 'description = "[^"]*"' | sed 's/description = "\([^"]*\)"/\1/')
            echo "_${desc}_" >> "$OUTPUT_DIR/companions.md"
            echo "" >> "$OUTPUT_DIR/companions.md"
        fi
    done

    # Get scale
    scale=$(grep -o "local SCALE = [0-9.]*" "$SRC_DIR/server/Companion.server.luau" 2>/dev/null | grep -o "[0-9.]*" || echo "Unknown")
    echo "" >> "$OUTPUT_DIR/companions.md"
    echo "## Stats" >> "$OUTPUT_DIR/companions.md"
    echo "- **Scale**: $scale" >> "$OUTPUT_DIR/companions.md"
fi

# ==========================================
# 9. STORY/NARRATIVE EXTRACTION
# ==========================================

echo -e "${BLUE}Extracting story elements...${NC}"

cat > "$OUTPUT_DIR/story-elements.md" << 'EOF'
# Story & Narrative Elements

## Story Signs Content
EOF

if [ -f "$SRC_DIR/server/Story.server.luau" ]; then
    echo '```' >> "$OUTPUT_DIR/story-elements.md"
    # Extract sign content
    grep -o 'content = "[^"]*"' "$SRC_DIR/server/Story.server.luau" 2>/dev/null | sed 's/content = "\([^"]*\)"/\1/' | head -20 >> "$OUTPUT_DIR/story-elements.md"
    echo '```' >> "$OUTPUT_DIR/story-elements.md"

    echo "" >> "$OUTPUT_DIR/story-elements.md"
    echo "## Doom System Warnings" >> "$OUTPUT_DIR/story-elements.md"
    echo '```' >> "$OUTPUT_DIR/story-elements.md"
    grep -o 'message = "[^"]*"' "$SRC_DIR/server/Story.server.luau" 2>/dev/null | sed 's/message = "\([^"]*\)"/\1/' >> "$OUTPUT_DIR/story-elements.md"
    echo '```' >> "$OUTPUT_DIR/story-elements.md"
fi

# ==========================================
# 10. SPATIAL RELATIONSHIPS
# ==========================================

echo -e "${BLUE}Analyzing spatial relationships...${NC}"

cat > "$OUTPUT_DIR/spatial-analysis.md" << 'EOF'
# Spatial Analysis

## Distance Matrix (Approximate)

Key locations and their relationships:

| From | To | Distance (studs) | Notes |
|------|-----|-----------------|-------|
| Spawn (0,0) | Frozen Peaks | ~500 | NW, uphill |
| Spawn (0,0) | Shadow Mtns | ~450 | NE, dangerous |
| Spawn (0,0) | Survivor Radio | ~150 | Close, safe music |
| Spawn (0,0) | Static FM | ~500 | North, creepy |
| Frozen Peaks | Shadow Mtns | ~600 | Mountain crossing |

## Zone Difficulty (Estimated by Distance from Spawn)

- **Safe Zone** (0-200 studs): Spawn area, Survivor Radio, initial resources
- **Medium Zone** (200-400 studs): Rivers, trading posts, some creatures
- **Danger Zone** (400+ studs): Mountains, Static FM, doom approaches

## Vertical Distribution

- **Ground Level**: Y = 0 (base terrain)
- **River Level**: Y = -1 to -2 (water beds)
- **Mountain Peaks**: Y = 200-400 (snow caps start ~200)
- **Radio Tower Lights**: Y = 60-100 (signal beacons)

EOF

# ==========================================
# FINAL SUMMARY
# ==========================================

echo -e "${BLUE}Generating summary...${NC}"

cat > "$OUTPUT_DIR/SUMMARY.md" << EOF
# Mertin-Flemmer Inspection Summary

Generated: $(date)

## Quick Stats

- **Total Server Scripts**: $(find "$SRC_DIR/server" -name "*.luau" | wc -l | tr -d ' ')
- **Total Client Scripts**: $(find "$SRC_DIR/client" -name "*.luau" 2>/dev/null | wc -l | tr -d ' ')
- **Total Shared Modules**: $(find "$SRC_DIR/shared" -name "*.luau" 2>/dev/null | wc -l | tr -d ' ')
- **Total Lines of Code**: $(find "$SRC_DIR" -name "*.luau" -exec cat {} \; | wc -l | tr -d ' ')

## Generated Reports

1. **world-layout.md** - Geographic features and positions
2. **world-map.txt** - ASCII representation of the world
3. **entity-inventory.md** - All scripts and their contents
4. **game-constants.md** - Extracted configuration values
5. **companions.md** - Camel personality details
6. **story-elements.md** - Narrative content and doom warnings
7. **spatial-analysis.md** - Distance and zone analysis

## Key Findings

### World Structure
- World size: ${WORLD_SIZE} studs
- 5 mountain ranges spread across quadrants
- 4 rivers winding through the landscape
- 6 radio stations at strategic positions

### Gameplay Systems
- Survival mechanics (hunger, hygiene, warmth)
- Companion system (5 camel personalities)
- Story progression with doom mechanic
- Mini-games (checkers with AI)
- Death/respawn with marker system

### Areas for Claude Review
Read these files to understand the game:
1. \`reports/world-map.txt\` - Visual layout
2. \`reports/story-elements.md\` - Narrative
3. \`reports/spatial-analysis.md\` - Zone design

EOF

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  INSPECTION COMPLETE${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Reports generated in: $OUTPUT_DIR/"
echo ""
ls -la "$OUTPUT_DIR/"
echo ""
echo -e "${YELLOW}Tip: Read these files to understand the world layout${NC}"
